apiVersion: v1
kind: Service
metadata:
  name: db # this will be the name shown to other apps 
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  ports: 
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
    app: demo-voting-app
    